<template>
  <section class="space-y-4">
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
      <div class="border rounded-lg p-4 space-y-3"><h3 class="font-semibold">{{ $t('brew.fermentation.log') }}</h3><label class="text-sm block">{{ $t('brew.fermentation.temperature') }}<input v-model="form.fermentationTemp" type="number" step="0.1" class="w-full mt-1 px-3 py-2 border rounded-md bg-background" /></label><label class="text-sm block">{{ $t('brew.fermentation.startedAt') }}<input v-model="form.fermentationStartedAt" type="datetime-local" class="w-full mt-1 px-3 py-2 border rounded-md bg-background" /></label><label class="text-sm block">{{ $t('brew.fermentation.transferredAt') }}<input v-model="form.transferDate" type="datetime-local" class="w-full mt-1 px-3 py-2 border rounded-md bg-background" /></label><label class="text-sm block">{{ $t('brew.fermentation.lageredAt') }}<input v-model="form.lagerDate" type="datetime-local" class="w-full mt-1 px-3 py-2 border rounded-md bg-background" /></label><button type="button" class="px-3 py-2 bg-primary text-primary-foreground rounded-md text-sm" @click="save">{{ $t('common.save') }}</button></div>
      <div class="border rounded-lg p-4 space-y-3"><h3 class="font-semibold">{{ $t('brew.fermentation.prediction') }}</h3><button type="button" class="px-3 py-2 border rounded-md text-sm" @click="predict">{{ $t('brew.fermentation.predictAbv') }}</button><pre v-if="prediction" class="text-xs whitespace-pre-wrap">{{ prediction }}</pre></div>
      <div class="border rounded-lg p-4 space-y-2"><h3 class="font-semibold">{{ $t('brew.fermentation.volumes') }}</h3><label class="text-sm block">{{ $t('brew.fermentation.volumeFermenter') }}<input v-model.number="form.volumeFermenter" type="number" step="0.1" class="w-full mt-1 px-3 py-2 border rounded-md bg-background" /></label><label class="text-sm block">{{ $t('brew.fermentation.waterAdded') }}<input v-model.number="form.waterAddedFermenter" type="number" step="0.1" class="w-full mt-1 px-3 py-2 border rounded-md bg-background" /></label></div>
    </div>
    <div class="border rounded-lg p-4 space-y-2"><h3 class="font-semibold">{{ $t('brew.fermentation.gravityReadings') }}</h3><BaseChart :option="gravityOption" height="280px" /><div v-for="row in gravityReadings" :key="row.id" class="flex justify-between text-sm border-t first:border-t-0 py-2"><span>{{ formatDate(row.datetime) }}</span><span class="font-mono">SG {{ row.sg ?? '—' }} · {{ row.tempS1 ?? '—' }} °C</span></div></div>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4"><div class="border rounded-lg p-4 space-y-2"><h3 class="font-semibold">{{ $t('brew.fermentation.yeastStarter') }}</h3><div class="grid grid-cols-6 gap-2 text-xs text-muted-foreground"><span>#</span><span>{{ $t('brew.fermentation.cellsIn') }}</span><span>L</span><span>SG</span><span>Mode</span><span>{{ $t('brew.fermentation.cellsOut') }}</span></div><div v-for="row in starterRows" :key="row.id" class="grid grid-cols-6 gap-2 text-sm border-t first:border-t-0 py-2"><span>#{{ row.stepNumber }}</span><span>{{ row.sourceVitality?.toFixed(1) }}</span><span>{{ row.wortVolume }}</span><span>{{ row.wortSg }}</span><span>{{ row.mode }}</span><span>{{ row.endingCells.toFixed(0) }}B</span></div><p v-if="!starterRows.length" class="text-sm text-muted-foreground">—</p></div><div class="border rounded-lg p-4 space-y-2"><h3 class="font-semibold">{{ $t('brew.fermentation.divisions') }}</h3><div v-for="row in brew.divisions" :key="row.id" class="text-sm border-t first:border-t-0 py-2">{{ row.splitDate || '—' }} · #{{ row.childBrewId ?? '—' }} · {{ row.volume }} L · {{ row.containerType }} · {{ row.notes || '—' }}</div><p v-if="!brew.divisions.length" class="text-sm text-muted-foreground">—</p></div></div>
  </section>
</template>
<script setup lang="ts">
import type { EChartsOption } from 'echarts'
import type { Brew, BrewDivision, BrewMeasurement, BrewYeastStarter } from '~/types'
import { cascadeStep, type PropagationMode } from '~/server/utils/calculations/yeast'
const props = defineProps<{ brew: Brew & { measurements: BrewMeasurement[]; yeastStarter: BrewYeastStarter[]; divisions: BrewDivision[] } }>()
const emit = defineEmits<{ save: [patch: Partial<Brew>] }>()
const form = reactive({ fermentationTemp: props.brew.fermentationTemp ?? undefined, fermentationStartedAt: '', transferDate: toLocalInput(props.brew.transferDate), lagerDate: toLocalInput(props.brew.lagerDate), volumeFermenter: props.brew.volumeFermenter ?? undefined, waterAddedFermenter: props.brew.waterAddedFermenter ?? undefined })
const prediction = ref('')
const gravityReadings = computed(() => props.brew.measurements.filter((row) => row.sg != null && row.sg > 0).sort((a,b)=>(a.datetime??'').localeCompare(b.datetime??'')))
const starterRows = computed(() => { let cells = 100; return [...props.brew.yeastStarter].sort((a,b)=>a.stepNumber-b.stepNumber).map((row) => { const start = (row.sourceVitality ?? 1) * cells; const result = cascadeStep(start, row.wortVolume ?? 0, row.wortSg ?? 1.04, (row.mode || 'simple') as PropagationMode); cells = result.endingCells; return { ...row, endingCells: result.endingCells, dmeGrams: result.dmeGrams } }) })
const gravityOption = computed<EChartsOption>(() => ({ tooltip:{trigger:'axis'}, grid:{left:48,right:24,top:20,bottom:48}, xAxis:{type:'category',data:gravityReadings.value.map((r)=>formatDate(r.datetime)), axisLabel:{rotate:30,fontSize:10}}, yAxis:{type:'value', min:'dataMin'}, series:[{name:'SG', type:'line', data:gravityReadings.value.map((r)=>r.sg)},{name:'Target FG', type:'line', symbol:'none', data:gravityReadings.value.map(()=>props.brew.fgActual || null)}] }))
function toLocalInput(value: string | null | undefined) { return value ? value.slice(0,16) : '' }
function toIso(value: string) { return value ? new Date(value).toISOString() : '' }
function formatDate(value: string | null | undefined) { return value ? new Date(value).toLocaleString() : '—' }
function save() { emit('save', { fermentationTemp: form.fermentationTemp, transferDate: toIso(form.transferDate), lagerDate: toIso(form.lagerDate), volumeFermenter: form.volumeFermenter, waterAddedFermenter: form.waterAddedFermenter, status: 'fermenting' }) }
async function predict() { const result = await $fetch(`/api/brews/${props.brew.id}/predict`); prediction.value = JSON.stringify(result, null, 2) }
</script>
